[project]
name = "time-tracker"
version = "0.1.0"
description = "App that tracks time"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.1.1",
]

 # In pyproject.toml
 [tool.setuptools.packages.find]
 where = ["."] # Look for packages in the current directory
 exclude = ["Docs*", "SqlScripts*"] # Exclude these directories
 # Or, to explicitly include only certain packages:
 # include = ["your_main_package_name*"]

[tool.pytest.ini_options]
env_files = [".env.test", ".env"]
