[project]
name = "time-tracker"
version = "0.1.0"
description = "App that tracks time"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "pydantic>=2.12.5",
    "pytest>=8.4.1",
    "pytest-cov>=6.3.0",
    "pytest-ini>=0.33",
    "pytest-mock>=3.14.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "rich>=14.3.2",
]

 # In pyproject.toml
 [tool.setuptools.packages.find]
 where = ["."] # Look for packages in the current directory
 exclude = ["Docs*", "SqlScripts*"] # Exclude these directories
 include = ["."]

[tool.pytest.ini_options]
env_files = [".env.test", ".env"]

[tool.coverage.run]
omit = ["*/test_*.py"]

